CREATE DATABASE IF NOT EXISTS Akemi_Motors;
USE Akemi_Motors;

CREATE TABLE IF NOT EXISTS carros (
    id INT AUTO_INCREMENT PRIMARY KEY,
    modelo VARCHAR(100) NOT NULL,
    preco VARCHAR(100) NOT NULL,
    quilometragem VARCHAR(100) NOT NULL,
    ano INT NOT NULL,
    imagem VARCHAR(255)
);